name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.0'

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install autoconf
        brew install automake
        brew install libtool

    - name: Build
      run: |
        swift run --package-path scripts
        
    - name: Update Package.swift
      run: |
        rm -f ./Package.swift
        cp -f ./docs/Package.template.swift ./Package.swift
        Libssl_url="https://github.com/mpvkit/openssl-build/releases/download/${{ github.event.inputs.version }}/Libssl.xcframework.zip"
        Libssl_checksum=$(cat ./dist/release/Libssl.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libssl_url)#${Libssl_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libssl_checksum)#${Libssl_checksum}#g" ./Package.swift

        Libcrypto_url="https://github.com/mpvkit/openssl-build/releases/download/${{ github.event.inputs.version }}/Libcrypto.xcframework.zip"
        Libcrypto_checksum=$(cat ./dist/release/Libcrypto.xcframework.checksum.txt)
        sed -i '' "s#\\\(Libcrypto_url)#${Libcrypto_url}#g" ./Package.swift
        sed -i '' "s#\\\(Libcrypto_checksum)#${Libcrypto_checksum}#g" ./Package.swift

    - name: Push Package.swift
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: |
          - Package.swift
          - Sources
        message: "chore: release version ${{ github.event.inputs.version }}"
        push: "origin HEAD:${{ github.ref_name }}"
        
    - name: Upload binary to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        files: |
          ./dist/release/*.txt
          ./dist/release/*.zip
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        fail_on_unmatched_files: true
